### ISSUE TITLE
DB에 채팅 시간 타임존이 맞지 않는 현상

### ISSUE THREAD

**Issue by SeongBeomKo** [thandbag/thandbag_BE#65]

**Comment by 59-devv** [comment]
1. AWS RDS 접속
2. 좌측 메뉴 중 '파라미터 그룹' 선택
3. '파라미터 그룹 생성' 클릭 (default는 수정이 불가능하므로 새로 생성해야 함. 아래 이미지 참조)
![image](https://user-images.githubusercontent.com/87135478/148580840-1a5fab41-4549-4b97-94ec-d770acd1224b.png)
 
4. '파라미터 그룹' 메뉴에서 새로 생성한 파라미터를 선택
5. time_zone을 선택한 후, 파라미터 편집을 누르고 'Asia/Seoul' 로 변경 (아래 이미지 참조)
![image](https://user-images.githubusercontent.com/87135478/148581150-52b104bb-100b-456c-ab4f-33d5119fa2ae.png)

6. 좌측 '데이터베이스' 메뉴를 클릭 후, DB 선택하고 '수정' 버튼 클릭
7. 아래 '추가 구성 -> 데이터베이스 옵션 -> DB 파라미터 그룹'에서, 생성 및 변경한 파라미터 그룹을 선택하고 변경사항 저장
![image](https://user-images.githubusercontent.com/87135478/148581536-fdc8f4bf-39e3-4c25-8cca-711a4cc2009c.png)

8. DB 인스턴스 재부팅 후, 새로운 데이터부터 변경된 timezone으로 변경됨
